export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const FETCH_CAROUSELS_REQUEST = "FETCH_CAROUSELS_REQUEST";
export const FETCH_CAROUSELS_SUCCESS = "FETCH_CAROUSELS_SUCCESS";
export const FETCH_CAROUSELS_FAILURE = "FETCH_CAROUSELS_FAILURE";
